// node.js module that provides devs with tools for working with file and directories
const path = require('path');
//exports a custom webpack module config in Node.js
module.exports = {
  //set the Webpack mode - fast builds, better debugging, no code minification
  mode: 'development', 
  // entry point for the Application, Webpack will monitor all the imports and dependencies on this file
  entry: './src/index.js', 
  // this object defines where the output should be after webpack processes 
  output: {
    // this is an absolute path - direct path to the endpoint bc of dunder dirname
    path: path.resolve(__dirname, 'dist'), // Output directory
    // this is the name of the JS file that is generated by webpack - will have all bundled modules and dpeendencies 
    filename: 'bundle.js', // Output file
    // base path that tells webpack where all assets and files will be served to , root of web server
    publicPath: '/', // Public path for serving files
  },
  // 
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/, // Process JS/JSX files
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.css$/, // Handle CSS imports
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.(png|jpg|gif)$/, // Handle image files
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'images/',
            },
          },
        ],
      },
    ],
  },
  devServer: {
    static: path.join(__dirname, 'public'), // Serve from public folder
    port: 9000, // You can specify the port here
    hot: true, // Enable hot reloading
    historyApiFallback: true, // Fallback to index.html for SPAs
  },
  resolve: {
    extensions: ['.js', '.jsx'], // Automatically resolve file extensions
  },
};
